### ISSUE TITLE
Conflicts with CARGO_TARGET_DIR

### ISSUE THREAD

**Issue by TriplEight** [NathanHowell/cargo-plan#2]
And possibly just with `target` dir filled with the relevant cache.

In general, it's a bit weird having to move into the dir and building new cache right there.

<details>
<summary>Repro:</summary>

```
docker run -it -v /home/user/cache/project/:/ci-cache/ paritytech/ci-linux:3ec7097e-20201113
```
And then
```
git clone https://github.com/paritytech/substrate .

export CARGO_TARGET_DIR=/ci-cache/target
cargo build --release -p subkey # building up cache as usual

cargo install --git https://github.com/NathanHowell/cargo-plan
cargo plan create
mkdir y
pushd y
cargo plan build -f ../cargo-plan.tar -- --release --package subkey
```

</details>

<details>
<summary>Error:</summary>

```
   Compiling sc-peerset v2.0.0 (/builds/y/client/peerset)
error: failed to run custom build command for `sc-network v0.8.0 (/builds/y/client/network)`

Caused by:
  process didn't exit successfully: `/ci-cache/target/release/build/sc-network-cca6e9df7ca8179f/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: src/schema: warning: directory does not exist.\nCould not make proto path relative: src/schema/api.v1.proto: No such file or directory\n" }', client/network/build.rs:8:58
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
     1: core::panicking::panic_fmt
               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
     2: core::option::expect_none_failed
               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
```

</details>

**Comment by NathanHowell** [comment]
@TriplEight yeah I was using the temp directory to verify the project would build, in reality this needs to be done with docker layers in the same directory. let me see if I can work up a better example

**Comment by TriplEight** [comment]
CIs do not use docker builder pattern widely, this doesn't scale.
What scales is sharing the cache between builds; pre-populating new branches with the cache from master, etc.

**Comment by TriplEight** [comment]
So ideal for my case would be your tmp dir matching with CARGO_TARGET_DIR or target dir by default

**Comment by NathanHowell** [comment]
let me take a look

**Comment by NathanHowell** [comment]
I think I've gotten it fixed in 885995e72aef77069df4146ad8b57971d1f2e900 but haven't tested it much yet, and that's all I can do for today. it seems that there can be an optimization using `cargo build --package <pkgid>` to avoid building local packages and having to clean the output, but I haven't figured out how to use it reliably yet.

Let me know if this helps or if you run into new errors.
